resume:
save_dir: models/
log_dir: ${name}/

metrics:
  accuracy:
    _target_: srcs.model.metric.accuracy
    _partial_: true
  top_k_acc:
    _target_: srcs.model.metric.top_k_acc
    _partial_: true

defaults:
  - _self_
  - data: mnist_train
  - model: mnist_lenet
  - hparams: lenet_baseline

  - status: train

  - working_dir: job_timestamp
  - override hydra/job_logging : custom
